// Code generated by mockery v1.0.0. DO NOT EDIT.

package visa

import mock "github.com/stretchr/testify/mock"

// MockVisasStorage is an autogenerated mock type for the VisasStorage type
type MockVisasStorage struct {
	mock.Mock
}

// GetPreviousVisas provides a mock function with given fields: name
func (_m *MockVisasStorage) GetPreviousVisas(name string) ([]Visa, error) {
	ret := _m.Called(name)

	var r0 []Visa
	if rf, ok := ret.Get(0).(func(string) []Visa); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Visa)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
